# Generated by Django 4.2.6 on 2023-10-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('testData_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('testData_name', models.CharField(max_length=100)),
                ('testData_position', models.CharField(max_length=100)),
                ('testData_office', models.CharField(max_length=100)),
                ('testData_age', models.IntegerField(default=0)),
                ('testData_startDate', models.DateField()),
                ('testData_salary', models.IntegerField(default=0)),
            ],
        ),
    ]
