# Generated by Django 4.2.6 on 2023-10-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='testData_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='testData_name',
            field=models.CharField(default='placeholder', max_length=100),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='testData_office',
            field=models.CharField(default='undecided', max_length=100),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='testData_position',
            field=models.CharField(default='undecided', max_length=100),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='testData_salary',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='testData_startDate',
            field=models.DateField(default='2023-10-31'),
        ),
    ]
