# Generated by Django 4.2.7 on 2023-11-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('testData_id', models.AutoField(primary_key=True, serialize=False)),
                ('testData_name', models.CharField(default='placeholder', max_length=100)),
                ('testData_position', models.CharField(default='undecided', max_length=100)),
                ('testData_office', models.CharField(default='undecided', max_length=100)),
                ('testData_age', models.IntegerField(default=0)),
                ('testData_startDate', models.DateField(default='2023-11-02')),
                ('testData_salary', models.IntegerField(default=1)),
            ],
        ),
    ]
