# Generated by Django 4.2.7 on 2023-11-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_testdata_testdata_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='testData_startDate',
            field=models.DateField(default='2023-11-06'),
        ),
    ]
