# Generated by Django 4.2.7 on 2023-11-02 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PiDigitData',
            fields=[
                ('id', models.AutoField(help_text='it is id and represent order of appearence', primary_key=True, serialize=False)),
                ('digit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PiRefData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_digit_0', models.ForeignKey(db_column='id_digit_0', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_0', to='pistore.pidigitdata')),
                ('id_digit_1', models.ForeignKey(db_column='id_digit_1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_1', to='pistore.pidigitdata')),
            ],
        ),
    ]
