# Generated by Django 4.2.7 on 2023-11-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='count',
            fields=[
                ('date', models.DateField(default='2023-11-04', primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('today', models.IntegerField()),
            ],
        ),
    ]
