# Generated by Django 4.2.7 on 2023-11-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_count_today_alter_count_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScore',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('answerColorR', models.IntegerField(default=0)),
                ('answerColorG', models.IntegerField(default=0)),
                ('answerColorB', models.IntegerField(default=0)),
                ('queryColorR', models.IntegerField(default=0)),
                ('queryColorG', models.IntegerField(default=0)),
                ('queryColorB', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0)),
                ('elapse', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='count',
            name='date',
            field=models.DateField(default='2023-11-06', primary_key=True, serialize=False),
        ),
    ]
