# Generated by Django 4.2.7 on 2023-11-06 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_colorscore_alter_count_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorscore',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
